[package]
name = "fun"
version = "0.1.0"
edition = "2021"

[lib]
# Unity Editor and funcli
crate-type = ["rlib", "cdylib"]
# macOS and Android
# crate-type = ["cdylib"]
# iOS and WebGL
# crate-type = ["staticlib"]

[dependencies]
